before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ raring main universe"
  - sudo apt-get update

  - sudo apt-get -y install ant
  - sudo apt-get -y install texlive-latex-base texlive-latex-recommended texlive-xetex
  - sudo apt-get -y install texlive-latex-extra texlive-fonts-recommended fonts-texgyre

  - sudo fc-cache -rsfv
  - fc-list

language: python

python:
  - "2.6"

env:
  - SPHINXOPTS="-W"

install: "pip install -q Sphinx"

script: "ant html pdf clean"
